### PR TITLE
Add support for external config files

### PR DESCRIPTION
**Pull request by oxc**
This change adds support for managing .conf.ext files that are passed as config values to userdb/passdb args for some drivers, as requested in #6

### CODE REVIEW

**Comment by oxc** [comment]
@c33s, can you please test this change whether it matches your requirements? Please note that managing `auth-sql.conf.ext` as a separate file is not supported by this change, but I would strongly advise against doing so anyway.

**Comment by c33s** [comment]
yes i test it. will report back here

**Comment by c33s** [comment]
one important thing: you want to be able to control the file creation mode easily. as these files contain the whole credentials to access the mail database, it must not be readable by others.

https://workaround.org/ispmail/stretch/setting-up-dovecot

> Finishing move
> 
> You should also make sure that only root can access the SQL configuration file so nobody else is reading your database access passwords:
> ```
>     chown root:root /etc/dovecot/dovecot-sql.conf.ext
>     chmod go= /etc/dovecot/dovecot-sql.conf.ext
> ````
>

**Comment by oxc** [comment]
The extconfig files now get a default mode of 0600, which can be configured using the `$mode` param of the global `dovecot::extconfigs_mode` parameter/hiera key.

**Comment by c33s** [comment]
you are right, it is not that important to manage the other ext files like `auth-sql.conf.ext`. i won't say it is completly unnessesary but far from needed in a puppet env.

the changes worked very well for me. the only serious issue is the permission thing noted above.

**Comment by oxc** [comment]
Have you noted my last commit and comment?

**Comment by oxc** [comment]
You can still manage separate files and include them from where you want, btw. This is already supported  by the module, just not with the default dovecot class. You would have to call the functions from your own profile class, so that the included files don't get automatically included in the main conf. Using a profile is recommended anyway for non-trivial puppet setups.
Plus currently the files will have to be named 
.conf, which is just cosmetics, though. Properly supporting other extensions would have meant introducing breaking changes, which is not something I'm willing to do for a feature I don't see the value of.
In fact I personally don't see any reason to even have more than one config file. You should not edit the files manually anyway, so any sorting/ordering can just as well be done in the yaml file with comments etc.
I understand that some people like to split the config into multiple conf.d files, but splitting out yet another layer of includes really does not live the puppet spirit.

**Comment by c33s** [comment]
sorry, haven't refreshed the git page and my mailserver is a little bit slow in delivering mails. have seen your comment and your commits not before today.

`Notice: /Stage[main]/Dovecot::Configuration/Dovecot::Extconfigfile[dovecot-sql.conf.ext]/File[dovecot external config file dovecot-sql.conf.ext]/mode: mode changed '0644' to '0600'`

works very well.

> You can still manage separate files and include them from where you want, ...

yes i know, i only prefer if the module class can handle the main files (like your module is doing it now). 

> Using a profile is recommended anyway for non-trivial puppet setups.
 
i already use a profile for dovecot but as i said, i really like your clean hiera syntax.
 

> Plus currently the files will have to be named `.conf`, which is just cosmetics, though. 

everything fine. nothing to worry about. really a good module. haven't signed in to puppetforge for ages but today i signed in to vote for your module. `conf.ext` also works.

> Properly supporting other extensions would have meant introducing breaking changes, which is not something I'm willing to do for a feature I don't see the value of.

+1

> In fact I personally don't see any reason to even have more than one config file. 

this is something i would not see like you of course you are right with the spirit of puppet but sometimes it is good that you split up the files that sysadmins who don't do puppet sees the files in their known places. often i have the problem, that people are in fear of new things. beeing as close as possible to their practice helps to introduce puppet silent.


thank you for your fast reaction and implementation of my feature request. thank you for your time.

**Comment by oxc** [comment]
> this is something i would not see like you of course you are right with the spirit of puppet but sometimes it is good that you split up the files that sysadmins who don't do puppet sees the files in their known places. often i have the problem, that people are in fear of new things. beeing as close as possible to their practice helps to introduce puppet silent.

Good point. And in fact I would have added support for `conf.d/*.conf.ext` files if it would have been possible in a nice way without possibly breaking existing setups. This way I feel it's just not worth it. Sorry if I came across a bit harsh.

**Comment by oxc** [comment]
Release on forge in v1.1.0

**Comment by c33s** [comment]
> Sorry if I came across a bit harsh.

nothing to worry about. i like direct communication and discussions. you simply made your point clear.

thanks for the release

**Pull request merged**
