### PR TITLE
refactoring and style fixes

### PR DESCRIPTION
**Pull request by fraenki**
I wanted to split this into several smaller PRs, but many changes depend on each other.

* add support for other operating systems
  * add defaults for RedHat, Debian and FreeBSD as module data
  * drop package_name function accordingly
* changes to comply with common practices
  * changes to module layout
    * split into standard classes: dovecot::install, dovecot::service, dovecot::configuration
  * changes to parameters
    * add new parameter `$service_enable`
    * add new parameter `$service_ensure`
    * add new parameter `$service_name` to customize the service name
    * add new parameter `$package_ensure` to allow 'latest' or a specific version number
    * rename parameter `$packages_install` to `$package_manage`
    * sort parameters alphabetically (whenever this is OK for puppet-lint)
* pet puppet-lint / style fixes
  * fix: indentation of => is not properly aligned
  * fix: ensure found on line but it's not the first attribute
  * fix: optional parameter listed before required parameter
  * use 2-space indentation everywhere
  * remove trailing whitespace
  * improve metadata quality
* bugs fixed
  * `require` on service would fail if `$package_manage` was `false`
* set required puppet version to 4.9 for Hiera 5 support

The renamed parameter is an backwards incompatible change, but I think it should be changed in the early days of this module. The new parameter name is used by hundreds of other modules.

### CODE REVIEW

**Comment by fraenki** [comment]
@oxc As discussed I've updated the documentation and hierarchy in https://github.com/oxc/puppet-dovecot/pull/1/commits/f46f9119145cad96b197d9d307da1627cb31a0b1. Furthermore I've fixed $service_enable.

**Comment by oxc** [comment]
@fraenki, as discussed, the package names should be merged into a unique list, as `managesieve` and `sieve` are provided by the same package on CentOS and FreeBSD.

**Comment by fraenki** [comment]
@oxc My latest commit adds the requested functionality to `install.pp`. This approach is more verbosive, but will still work if we introduce other parameters alongside `package_name`.

Besides that I've added `package_name` for `sieve` on FreeBSD and CentOS.

**Comment by oxc** [comment]
@fraenki: thanks for your work!

**Pull request merged**
