### PR TITLE
update puppet/archive version and add 18.04

### PR DESCRIPTION
**Pull request by mgariepy**
* update puppet-archive to 3.2.1  
* add ubuntu 18.04 to supported os version

### CODE REVIEW

**Comment by oxc** [comment]
Thanks!

I think it's safe to bump the version requirement to < 4.0.0

Would you mind squashing the commits?

**Comment by mgariepy** [comment]
done, thanks.

**Comment by mgariepy** [comment]
@ocx  Can you please cut a new release including this change ? perhaps 2.0.1.

thanks

**Comment by oxc** [comment]
Released in [v2.1.0](https://github.com/oxc/puppet-dovecot/releases/tag/v2.1.0)

**Pull request merged**
